## Command Topic
#- topic_name: "cmd_vel"
#  ros_type_name: "geometry_msgs/msg/Twist"
#  gz_type_name: "ignition.msgs.Twist"
#
## Lidar Topic
#- topic_name: "lidar"
#  ros_type_name: "sensor_msgs/msg/LaserScan"
#  gz_type_name: "ignition.msgs.LaserScan"
#
## Imu Topic
#- topic_name: "imu"
#  ros_type_name: "sensor_msgs/msg/Imu"
#  gz_type_name: "ignition.msgs.IMU"
#
#- ros_topic_name: "tf"
#  gz_topic_name: "model/wheelchair/tf"
#  ros_type_name: "tf2_msgs/msg/TFMessage"
#  gz_type_name: "ignition.msgs.Pose_V"
#
#- ros_topic_name: "odom"
#  gz_topic_name: "model/wheelchair/odometry"
#  ros_type_name: "nav_msgs/msg/Odometry"
#  gz_type_name: "ignition.msgs.Odometry"
#
#
## Joint State
#
#- ros_topic_name: "joint_states"
#  gz_topic_name: "world/world_corridor/model/wheelchair/joint_state"
#  ros_type_name: "sensor_msgs/msg/JointState"
#  gz_type_name: "ignition.msgs.Model"
---
- topic_name: "cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

- topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "odom"
  gz_topic_name: "model/wheelchair/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "scan"
  gz_topic_name: "lidar"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS
# Imu Topic
- topic_name: "imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "joint_states"
  gz_topic_name: "world/world_corridor/model/wheelchair/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "tf"
  gz_topic_name: "model/wheelchair/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# - ros_topic_name: "tf_static"
#   gz_topic_name: "model/wheelchair/pose_static"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "gz.msgs.Pose_V"
#   direction: GZ_TO_ROS

